"""FABLE nightly generator — regenerates trade-log + portfolio markdown for
every FABLE strategy into strategy-leaderboard/data/fable/.

Usage:
  python -m fable_engine.generate                 # all strategies
  python -m fable_engine.generate --variant KEY   # one strategy
  python -m fable_engine.generate --git-commit    # commit + push results

Data: reads the shared OHLC caches (equities yfinance cache refreshed by the
existing Stock Nightly step 1; crypto Kraken cache refreshed by step 3). This
generator performs NO fetching of its own — run it AFTER those steps.
"""
from __future__ import annotations
import argparse
import datetime as dt
import subprocess
from pathlib import Path

import pandas as pd

from .strategies import CONFIGS, SIGNALS, FableConfig, _load, PAPER_START_ISO, LIVE_START_ISO
from .engine import simulate, SimulationResult

HERE = Path(__file__).resolve().parent
LEADERBOARD = Path(r"C:\trading\strategy-leaderboard")
OUT_DIR = LEADERBOARD / "data" / "fable"
DEFAULT_STARTING_CAPITAL = 10000.0


def _to_unix(iso: str) -> int:
    return int(dt.datetime.fromisoformat(iso.replace("Z", "+00:00")).timestamp())


def _utc_now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _fmt_num(v, decimals: int = 6) -> str:
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "\u2014"
    if isinstance(v, float):
        s = f"{v:.{decimals}f}".rstrip("0").rstrip(".")
        return s or "0"
    return str(v)


def _fmt_signed(v, decimals: int = 2) -> str:
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "\u2014"
    sign = "+" if v >= 0 else ""
    return f"{sign}{v:.{decimals}f}"


def build_signals(cfg: FableConfig, start_unix: int) -> dict:
    fn = SIGNALS[cfg.signal_builder]
    out = {}
    import time as _time
    end_unix = int(_time.time())
    for sym in cfg.universe:
        intraday, higher = _load(sym, cfg)
        df = fn(intraday, higher, cfg)
        df = df[(df["time"] >= start_unix) & (df["time"] < end_unix)].reset_index(drop=True)
        out[sym] = df
    return out


def render_trade_log(cfg: FableConfig, sim: SimulationResult, generated_at: str) -> str:
    n = len(sim.closed_pnls)
    wins = [p for p in sim.closed_pnls if p > 0]
    win_pct = round(100.0 * len(wins) / n, 1) if n else 0.0
    avg_r = round(sum(sim.closed_r_multiples) / len(sim.closed_r_multiples), 3) if sim.closed_r_multiples else 0.0
    lines = [
        f"# {cfg.display_name} \u2014 Trade Log",
        "",
        "> **Auto-generated by `fable_engine.generate`. Do not edit by hand.**",
        f"> **Last regenerated:** {generated_at}",
        f"> **Paper backfill start:** {PAPER_START_ISO}",
        f"> **Live start (honest creation date):** {LIVE_START_ISO} _(pre-live trades are backtest; excluded from contest equity by the adapter)_",
        f"> **Owner:** FABLE (Claude Fable 5) \u2014 independent competitor, entered 2026-06-10",
        f"> **Venue:** {cfg.venue}",
        f"> **Edge:** {cfg.edge_line}",
        f"> **Risk/trade:** {cfg.risk_per_trade*100:.2f}%  |  **Heat cap:** {cfg.max_concurrent}  |  **Daily loss circuit:** {cfg.daily_loss_pct*100:.1f}%  |  **Commission RT:** {cfg.commission_pct_roundtrip*100:.2f}%",
        f"> **Entry:** {cfg.entry_line}",
        f"> **Exit:** {cfg.exit_line}",
        "",
        "## Summary",
        "",
        f"- Closed events: **{n}**",
        f"- Win rate: **{win_pct}%**",
        f"- Average R-multiple per closed leg: **{avg_r:+.3f}**",
        f"- Realized PnL (cumulative): **{_fmt_signed(sim.realized_pnl_total)}**",
        f"- Ending equity: **{sim.ending_equity:.2f}** (started {sim.starting_equity:.2f})",
        f"- Open at end: **{len(sim.open_at_end)}**",
        "",
        "## Schema",
        "",
        "| Timestamp (UTC) | Event | Pair | Side | Size | Price | Stop | Target | R at exit | Realized PnL | Reason tag |",
        "|-----------------|-------|------|------|------|-------|------|--------|-----------|--------------|------------|",
        "",
        "## Entries",
        "",
    ]
    if not sim.events:
        lines.append("_No trade events in window yet._")
    else:
        dash = "\u2014"
        for ev in sim.events:
            r_txt = _fmt_signed(ev['r'], 3) if ev['r'] is not None else dash
            pnl_txt = _fmt_signed(ev['pnl'], 4) if ev['pnl'] is not None else dash
            lines.append(
                f"| {ev['time']} | {ev['action']} | {ev['symbol']} | {ev['side']} "
                f"| {_fmt_num(ev['size'], 6)} | {_fmt_num(ev['price'], 4)} "
                f"| {_fmt_num(ev['stop'], 4)} | {dash} "
                f"| {r_txt} "
                f"| {pnl_txt} "
                f"| {ev['reason']} |"
            )
    return "\n".join(lines) + "\n"


def render_portfolio(cfg: FableConfig, sim: SimulationResult, generated_at: str) -> str:
    cash = sim.starting_equity + sim.realized_pnl_total
    unreal = sum(p.get("unrealized", 0.0) for p in sim.open_at_end)
    mtm_equity = cash + unreal
    dd = max(0.0, (sim.starting_equity - mtm_equity) / sim.starting_equity * 100.0)
    body = (
        f"# {cfg.display_name} \u2014 Portfolio Snapshot\n\n"
        f"> Auto-generated by `fable_engine.generate`. Last regenerated: {generated_at}\n\n"
        f"- Cash: **{cash:.2f}**\n"
        f"- Realized PnL (cumulative): **{_fmt_signed(sim.realized_pnl_total)}**\n"
        f"- Unrealized PnL (marked to latest cached close, net of est. fees): **{_fmt_signed(unreal)}**\n"
        f"- Current equity (MTM): **{mtm_equity:.2f}**\n"
        f"- Equity peak: **{max(sim.starting_equity, mtm_equity):.2f}**\n"
        f"- Drawdown from peak (MTM): **{dd:.2f}%**\n\n"
        f"## Open positions ({len(sim.open_at_end)})\n\n"
    )
    if sim.open_at_end:
        body += "| Symbol | Side | Entry | Last | Stop | Size | Unrealized | Entry time | Bars held |\n"
        body += "|--------|------|-------|------|------|------|------------|------------|-----------|\n"
        body += "\n".join(
            f"| {p['symbol']} | {p['side']} | {p['entry']:.4f} | {p['last_close']:.4f} | {p['stop']:.4f} | {p['size']:.4f} | {_fmt_signed(p['unrealized'])} | {p['entry_time']} | {p['bars_held']} |"
            for p in sim.open_at_end
        )
    else:
        body += "_No open positions._"
    return body + "\n"


def git_commit(keys: list, generated_at: str) -> None:
    rels = []
    for k in keys:
        rels.append(str((OUT_DIR / f"{k}_trade_log.md").relative_to(LEADERBOARD)))
        rels.append(str((OUT_DIR / f"{k}_portfolio.md").relative_to(LEADERBOARD)))
    subprocess.run(["git", "-C", str(LEADERBOARD), "add", "--", *rels], check=True)
    diff = subprocess.run(["git", "-C", str(LEADERBOARD), "diff", "--cached", "--quiet"], check=False)
    if diff.returncode == 0:
        print("[git] no changes", flush=True)
        return
    msg = f"fable nightly: regenerated {len(keys)} strategies {generated_at}"
    subprocess.run(["git", "-C", str(LEADERBOARD), "commit", "-m", msg], check=True)
    push = subprocess.run(["git", "-C", str(LEADERBOARD), "push"], check=False)
    if push.returncode != 0:
        print("[git] push failed (committed locally)", flush=True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default=None, choices=list(CONFIGS))
    ap.add_argument("--git-commit", action="store_true")
    ap.add_argument("--starting-equity", type=float, default=DEFAULT_STARTING_CAPITAL)
    args = ap.parse_args()

    keys = [args.variant] if args.variant else list(CONFIGS)
    start_unix = _to_unix(PAPER_START_ISO)
    generated_at = _utc_now_iso()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for key in keys:
        cfg = CONFIGS[key]
        print(f"[fable] {cfg.display_name}", flush=True)
        signals = build_signals(cfg, start_unix)
        sim = simulate(signals, cfg, args.starting_equity)
        print(f"  events: {len(sim.events)}  closed: {len(sim.closed_pnls)}  realized: {sim.realized_pnl_total:+.2f}", flush=True)
        (OUT_DIR / f"{key}_trade_log.md").write_text(render_trade_log(cfg, sim, generated_at), encoding="utf-8")
        (OUT_DIR / f"{key}_portfolio.md").write_text(render_portfolio(cfg, sim, generated_at), encoding="utf-8")

    if args.git_commit:
        git_commit(keys, generated_at)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


